package com.tct.tctcampaign.rowmapper;

import com.tct.tctcampaign.model.db.Survey;
import com.tct.tctcampaign.model.db.User;
import org.springframework.jdbc.core.RowMapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Objects;

public class SurveyRowMapper implements RowMapper<Survey> {
    @Override
    public Survey mapRow(ResultSet rs, int rowNum) throws SQLException {
        Survey obj = new Survey();
        if(Objects.nonNull(rs)){
            obj.setId(rs.getInt("ID"));
            obj.setFormNo(rs.getInt("Form_no"));
            obj.setDistrict(rs.getString("District"));
            obj.setTaluk(rs.getString("Taluk"));
            obj.setBlock(rs.getString("Block"));
            obj.setPanchayat(rs.getString("Panchayat"));
            obj.setAreaCode(rs.getString("Area_Code"));
            obj.setVillageCode(rs.getString("Village_Code"));
            obj.setVillage(rs.getString("Village"));
            obj.setStreetName(rs.getString("Street_Name"));
            obj.setDoorNo(rs.getString("Door_No"));
            obj.setRespondentName(rs.getString("Respondent_Name"));
            obj.setMobileNo(rs.getString("Mobile_No"));
            obj.setIsSmartPhone(rs.getString("Is_SmartPhone"));
            obj.setFamilyCaste(rs.getString("Family_Caste"));
            obj.setSubCaste(rs.getString("Sub_Caste"));
            obj.setFamilyId(rs.getString("Family_Id"));
            obj.setDateofConnection(rs.getString("Date_of_Connection"));
            obj.setMemberName(rs.getString("Member_Name"));
            obj.setGender(rs.getString("Gender"));
            obj.setRelationshiptoHead(rs.getString("Relationship_to_Head"));
            obj.setFamilyPositionNumber(rs.getInt("Family_Position_Number"));
            obj.setDateofBirth(rs.getString("Date_of_Birth"));
            obj.setAge(rs.getInt("Age"));
            obj.setEducationalStatus(rs.getString("Educational_Status"));
            obj.setMaritalStatus(rs.getString("Marital_Status"));
            obj.setOccupation(rs.getString("Occupation"));
            obj.setIsRetired(rs.getString("Is_Retired"));
            obj.setAnnualIncome(rs.getInt("Annual_Income"));
            obj.setTMHId(rs.getString("TMHId"));
            obj.setPatientId(rs.getString("Patient_Id"));
            obj.setIsDead(rs.getString("Is_Dead"));
            obj.setDateofDeath(rs.getString("Date_of_Death"));
            obj.setTotalIncome(rs.getInt("Total_Income"));
            obj.setStatusofHouse(rs.getString("Status_of_House"));
            obj.setTypeofHouse(rs.getString("Type_of_House"));
            obj.setWetLandHoldingInAcres(rs.getFloat("Wet_Land_Holding_In_Acres"));
            obj.setDryLandHoldingInAcres(rs.getFloat("Dry_Land_Holding_In_Acres"));
            obj.setNumberofvariousMotorvechiclesowned(rs.getString("Number_of_various_Motor_vechicles_owned"));
            obj.setLivestocksDetails(rs.getString("Livestocks_Details"));
            obj.setToiletFacilityatHome(rs.getString("Toilet_Facility_at_Home"));
            obj.setGovernmentInsuranceHealthInsurance(rs.getString("Government_Insurance_Health_Insurance"));
            obj.setPrivateInsuranceHealthInsurance(rs.getString("Private_Insurance_Health_Insurance"));
            obj.setOldagepension(rs.getString("Old_age_pension"));
            obj.setWidowedPension(rs.getString("Widowed_Pension"));
            obj.setRetirementPension(rs.getString("Retirement_Pension"));
            obj.setOtherFinancialAssisantSchemes(rs.getString("Other_Financial_Assisant_Schemes"));
            obj.setSmokingMembers(rs.getString("Smoking_Member_s"));
            obj.setAlcoholMembers(rs.getString("Alcohol_Member_s"));
            obj.setTabaccoMembers(rs.getString("Tabacco_Member_s"));
            obj.setForMinorProblems(rs.getString("For_Minor_Problems"));
            obj.setForMajorProblems(rs.getString("For_Major_Problems"));
            obj.setProvideDetailsofPrivateDoctorsHospitalsClinicswhereyoumayvisit(rs.getString("Provide_Details_of_Private_Doctors_Hospitals_Clinics_where_you_may_visit"));
            obj.setInyourfamilyisanyonesufferingfromfollowingdiseases(rs.getString("In_your_family_is_any_one_suffering_from_following_diseases"));
            obj.setOrtho(rs.getString("Ortho"));
            obj.setAnemia(rs.getString("Anemia"));
            obj.setAsthma(rs.getString("Asthma"));
            obj.setBloodPressure(rs.getString("Blood_Pressure"));
            obj.setCold(rs.getString("Cold"));
            obj.setCough(rs.getString("Cough"));
            obj.setStress(rs.getString("Stress"));
            obj.setDiabetes(rs.getString("Diabetes"));
            obj.setENTInfection(rs.getString("ENT_Infection"));
            obj.setEyeProblem(rs.getString("Eye_Problem"));
            obj.setFever(rs.getString("Fever"));
            obj.setElephantiasis(rs.getString("Elephantiasis"));
            obj.setGynaecological(rs.getString("Gynaecological"));
            obj.setHeadache(rs.getString("Headache"));
            obj.setJaundice(rs.getString("Jaundice"));
            obj.setHeartProblems(rs.getString("Heart_Problems"));
            obj.setPediatric(rs.getString("Pediatric"));
            obj.setKidneyProblems(rs.getString("Kidney_Problems"));
            obj.setMalaria(rs.getString("Malaria"));
            obj.setNeuro(rs.getString("Neuro"));
            obj.setLung(rs.getString("Lung"));
            obj.setObesityCholesterol(rs.getString("Obesity_Cholesterol"));
            obj.setSkinProblems(rs.getString("Skin_Problems"));
            obj.setStomachProblems(rs.getString("Stomach_Problems"));
            obj.setToothache(rs.getString("Toothache"));
            obj.setTB(rs.getString("TB"));
            obj.setWounds(rs.getString("Wounds"));
            obj.setThyroid(rs.getString("Thyroid"));
            obj.setHernia(rs.getString("Hernia"));
            obj.setChickenPox(rs.getString("ChickenPox"));
            obj.setCancer(rs.getString("Cancer"));
            obj.setParalysis(rs.getString("Paralysis"));
            obj.setOthers(rs.getString("Others"));
            obj.setBreastProblems(rs.getString("Breast_Problems"));
            obj.setUterusProblmes(rs.getString("Uterus_Problmes"));
            obj.setPersoneligibleButnotscreened(rs.getString("Person_eligible_But_not_screened"));
            obj.setBreastorUterusCancer(rs.getString("Breast_or_Uterus_Cancer"));
            obj.setIfscreenedwherehavetheybeenscreened(rs.getString("If_screened_where_have_they_been_screened"));
            obj.setIsdiagnosedascancer(rs.getString("Is_diagnosed_as_cancer"));
            obj.setIfyeswherehavetheybeentreated(rs.getString("If_yes_where_have_they_been_treated"));
            obj.setFamilyPositionNumbersofanymentallyretardedpersons(rs.getString("Family_Position_Numbers_of_any_mentally_retarded_persons"));
            obj.setAvailedGovtbenefits(rs.getString("Availed_Govt_benefits"));
            obj.setWhatsortofbenefits(rs.getString("What_sort_of_benefits"));
            obj.setArethosewithmentalillnesstakinganytreatment(rs.getString("Are_those_with_mental_illness_taking_any_treatment"));
            obj.setHandicapPersonName(rs.getString("Handicap_Person_Name"));
            obj.setHandicapType(rs.getString("Handicap_Type"));
            obj.setHaveIDcardforphysicallychallengedpersons(rs.getString("Have_ID_card_for_physically_challenged_persons"));
            obj.setWhetheravailedGovtbenefits(rs.getString("Whether_availed_Govt_benefits"));
            obj.setWhatsortofgovtbenefits(rs.getString("What_sort_of_govt_benefits"));
            obj.setInyourfamilyisanyonesufferingfromNCDs(rs.getString("In_your_family_is_any_one_suffering_from_NCD_s"));
            obj.setNCDDiabetes(rs.getString("NCD_Diabetes"));
            obj.setNCDBloodPressure(rs.getString("NCD_Blood_Pressure"));
            obj.setOsteoporosis(rs.getString("Osteoporosis"));
            obj.setUterusCancer(rs.getString("Uterus_Cancer"));
            obj.setBreastCancer(rs.getString("Breast_Cancer"));
            obj.setOralCancer(rs.getString("Oral_Cancer"));
            obj.setObesity(rs.getString("Obesity"));
            obj.setHeartDiseases(rs.getString("Heart_Diseases"));
            obj.setLungRelatedDiseases(rs.getString("Lung_Related_Diseases"));
            obj.setNCDAsthma(rs.getString("NCD_Asthma"));
            obj.setJointPain(rs.getString("JointPain"));
            obj.setNCDParalysis(rs.getString("NCD_Paralysis"));
            obj.setAlcoholic(rs.getString("Alcoholic"));
            obj.setNCDOthers(rs.getString("NCD_Others"));
        }
        return obj;
    }
}
