package com.tct.tctcampaign.model.db;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Survey {
    private int id;
    private int formNo;
    private String district ;
    private String taluk ;
    private String block ;
    private String panchayat ;
    private String areaCode ;
    private String villageCode ;
    private String village ;
    private String streetName ;
    private String doorNo ;
    private String respondentName ;
    private String mobileNo ;
    private String isSmartPhone ;
    private String familyCaste ;
    private String subCaste ;
    private String familyId ;
    private String dateofConnection ;
    private String memberName ;
    private String gender ;
    private String relationshiptoHead ;
    private int familyPositionNumber;
    private String dateofBirth ;
    private int age;
    private String educationalStatus ;
    private String maritalStatus ;
    private String occupation ;
    private String isRetired ;
    private int annualIncome;
    private String TMHId ;
    private String patientId ;
    private String isDead ;
    private String dateofDeath ;
    private int totalIncome;
    private String statusofHouse ;
    private String typeofHouse ;
    private float wetLandHoldingInAcres;
    private float dryLandHoldingInAcres;
    private String numberofvariousMotorvechiclesowned ;
    private String livestocksDetails ;
    private String toiletFacilityatHome ;
    private String governmentInsuranceHealthInsurance ;
    private String privateInsuranceHealthInsurance ;
    private String oldagepension ;
    private String widowedPension ;
    private String retirementPension ;
    private String otherFinancialAssisantSchemes ;
    private String smokingMembers ;
    private String alcoholMembers ;
    private String tabaccoMembers ;
    private String forMinorProblems ;
    private String forMajorProblems ;
    private String provideDetailsofPrivateDoctorsHospitalsClinicswhereyoumayvisit ;
    private String inyourfamilyisanyonesufferingfromfollowingdiseases ;
    private String ortho ;
    private String anemia ;
    private String asthma ;
    private String bloodPressure ;
    private String cold ;
    private String cough ;
    private String stress ;
    private String diabetes ;
    private String ENTInfection ;
    private String eyeProblem ;
    private String fever ;
    private String elephantiasis ;
    private String gynaecological ;
    private String headache ;
    private String jaundice ;
    private String heartProblems ;
    private String pediatric ;
    private String kidneyProblems ;
    private String malaria ;
    private String neuro ;
    private String lung ;
    private String obesityCholesterol ;
    private String skinProblems ;
    private String stomachProblems ;
    private String toothache ;
    private String tB ;
    private String wounds ;
    private String thyroid ;
    private String hernia ;
    private String chickenPox ;
    private String cancer ;
    private String paralysis ;
    private String others ;
    private String breastProblems ;
    private String uterusProblmes ;
    private String personeligibleButnotscreened ;
    private String breastorUterusCancer ;
    private String ifscreenedwherehavetheybeenscreened ;
    private String isdiagnosedascancer ;
    private String ifyeswherehavetheybeentreated ;
    private String familyPositionNumbersofanymentallyretardedpersons ;
    private String availedGovtbenefits ;
    private String whatsortofbenefits ;
    private String arethosewithmentalillnesstakinganytreatment ;
    private String handicapPersonName ;
    private String handicapType ;
    private String haveIDcardforphysicallychallengedpersons ;
    private String whetheravailedGovtbenefits ;
    private String whatsortofgovtbenefits ;
    private String inyourfamilyisanyonesufferingfromNCDs ;
    private String NCDDiabetes ;
    private String NCDBloodPressure ;
    private String osteoporosis ;
    private String uterusCancer ;
    private String breastCancer ;
    private String oralCancer ;
    private String obesity ;
    private String heartDiseases ;
    private String lungRelatedDiseases ;
    private String NCDAsthma ;
    private String jointPain;
    private String NCDParalysis ;
    private String alcoholic ;
    private String NCDOthers ;
}
