package com.tct.tctcampaign.model.db;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class SurveyView {
    private String familyId;
    private String blockName;
    private String panchayat;
    private Integer areaCode;
    private String villageCode;
    private String villageName;
    private String streetName;
    private String statusOfHouse;
    private String typeOfHouse;
    private String wetLandInAcres;
    private String dryLandInAcres;
    private String motorVechicles;
    private String twoWheeler;
    private String fourWheeler;
    private String noOtherVechicles;
    private String otherVechiclesDetails;
    private String livestockDetails;
    private String hen;
    private String cow;
    private String pig;
    private String buffalo;
    private String goat;
    private String noOtherLivestock;
    private String otherLivestockDetails;
    private String toiletFacilityAtHome;
    private Long memberId;
    private String memberName;
    private String aadharNumber;
    private String mobileNumber;
    private String email;
    private String smartphone;
    private String govtInsurance;
    private String privateInsurance;
    private String oldAgePension;
    private String widowedPension;
    private String retiredPerson;
    private String vaccination;
    private Date doseOne;
    private Date doseTwo;
    private Date birthDate;
    private String smoking;
    private String drinking;
    private String tobacco;
    private String diabetes;
    private String bp;
    private String osteoporosis;
    private String breastCancer;
    private String uterusCancer;
    private String uterusCancerScan;
    private String breastCancerScan;
    private String oralCancer;
    private String obesity;
    private String heartDiseases;
    private String lungRelatedDiseases;
    private String asthma;
    private String jointPain;
    private String otherDiseases;
    private String annualIncomeString;
    private String isDeceased;
    private Date deceasedDate;
    private String isOsteoporosisScan;
    private String osteoporosisScanOne;
    private String osteoporosisScanTwo;
    private String imageLocation;
    private String tmhId;
    private String patientId;
    private String permanentSterlization;
    private Date permanentSterlizationDate;
    private String tmpSterlization;
    private String tmpSterlizationType;
    private Date diabeticEnrolmentDate;
    private String diabeticEnrollmentStatus;
    private Date diabeticEnrollmentEndDate;
    private String diabeticPackage;
    private String gender;
    private String physicallyChallenged;
    private String handicapType;
    private String occupation;
    private String age;
    private String community;
    private String caste;
    private String relationship;
    private String martialStatus;
    private String bloodGroup;
    private String educationQualification;
}
